// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/22/2025, 1:06:52 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/plugins/**/*.{js,ts,mjs}","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/composables/**/*.{js,ts,mjs}","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/utils/**/*.{js,ts,mjs}","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/pages/about.vue","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/pages/index.vue","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/christianlund/Documents/GitHub/Fur-Bryghus/my-nuxt-app/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;